name: Validation Tests

on:
  pull_request:
    branches:
      - main

jobs:
  Validation-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "0800"
          envkey_POSTGRES_DB: "students_test"
          envkey_DATABASE_URL: "postgresql://postgres:0800@postgres_students_db:5432/students_test"
          file_name: ".env.test"
      - name: Run Tests
        run: docker-compose -f docker-compose-tests.yml run node_students_app npm run test:merge